"""empty message

Revision ID: 4d094c2d8f04
Revises: c94db49ad4dc
Create Date: 2025-04-22 08:06:29.036189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d094c2d8f04'
down_revision = 'c94db49ad4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_bill_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('neg', sa.String(length=50), nullable=True),
    sa.Column('ropeh', sa.String(length=50), nullable=True),
    sa.Column('total', sa.String(length=50), nullable=True),
    sa.Column('chungi', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_bill_record')
    # ### end Alembic commands ###
