"""empty message

Revision ID: 887d9673229a
Revises: 4d094c2d8f04
Create Date: 2025-04-29 07:31:38.929876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '887d9673229a'
down_revision = '4d094c2d8f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bill_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_bill_record', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
