"""empty message

Revision ID: 9803637d2d09
Revises: 1c783ab36a86
Create Date: 2025-02-17 20:52:44.777098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9803637d2d09'
down_revision = '1c783ab36a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costumer_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('other_balance', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('banana_melon_balance', sa.String(length=20), nullable=True))
        batch_op.drop_index('email')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
        batch_op.create_index('email', ['email'], unique=True)
        batch_op.drop_column('banana_melon_balance')
        batch_op.drop_column('other_balance')
        batch_op.drop_column('costumer_type')

    # ### end Alembic commands ###
