"""empty message

Revision ID: a1faf2dfba23
Revises: 9803637d2d09
Create Date: 2025-02-17 21:20:09.759104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1faf2dfba23'
down_revision = '9803637d2d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_type', sa.String(length=20), nullable=False))
        batch_op.drop_column('costumer_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costumer_type', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('customer_type')

    # ### end Alembic commands ###
