"""empty message

Revision ID: c94db49ad4dc
Revises: a1faf2dfba23
Create Date: 2025-04-15 10:17:42.127041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94db49ad4dc'
down_revision = 'a1faf2dfba23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('maarkah', sa.String(length=20), nullable=True),
    sa.Column('car_number', sa.String(length=20), nullable=True),
    sa.Column('total_nagg', sa.Integer(), nullable=False),
    sa.Column('kham_bikri', sa.Integer(), nullable=False),
    sa.Column('rent_laari', sa.Integer(), nullable=True),
    sa.Column('mazdoori', sa.Integer(), nullable=True),
    sa.Column('daag', sa.Integer(), nullable=True),
    sa.Column('munshiyana', sa.Integer(), nullable=True),
    sa.Column('market_fees', sa.Integer(), nullable=True),
    sa.Column('chungi', sa.Integer(), nullable=True),
    sa.Column('amanat', sa.Integer(), nullable=True),
    sa.Column('custom', sa.Integer(), nullable=True),
    sa.Column('extra_rent', sa.Integer(), nullable=True),
    sa.Column('commission', sa.Integer(), nullable=True),
    sa.Column('pukhta_bikri', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date_entered', sa.DateTime(), nullable=True),
    sa.Column('date_out', sa.DateTime(), nullable=True),
    sa.Column('wasool', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_customer_details',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('neg', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'customer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_customer_details')
    op.drop_table('bill')
    # ### end Alembic commands ###
